name: mono_repo_starter

packages:
  - packages/**
  - mapp
  - sapp
  - km

scripts:
  kmPubGet:
    exec: flutter clean && flutter pub get
  kmGenResp:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
  mappPubGet:
    run: melos exec --ignore="km_*" "flutter clean && flutter pub get"
  mappGenResp:
    run: melos exec --ignore="km_*" "flutter clean && flutter pub get"