name: mono_repo_starter

packages:
  - packages/**
  - mapp
#  - sapp

scripts:
  pubGet:
    exec: flutter clean && flutter pub get
  genResp:
    exec: flutter pub run build_runner build --delete-conflicting-outputs